-- Query the database for City info --
SELECT * FROM CITY WHERE COUNTRYCODE='USA' AND POPULATION > 100000;
SELECT NAME FROM CITY WHERE POPULATION > 120000 AND COUNTRYCODE='USA';
SELECT * FROM CITY;
SELECT * FROM CITY WHERE COUNTRYCODE='JPN';
SELECT * FROM CITY WHERE ID=1661;
SELECT NAME FROM CITY WHERE COUNTRYCODE='JPN';